# Generated by Django 4.1.7 on 2023-10-06 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_group_datecreated_alter_module_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 9, 47, 48, 919902)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 9, 47, 48, 919902)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 9, 47, 48, 919902)),
        ),
    ]
