# Generated by Django 4.1.7 on 2023-10-06 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_group_datecreated_alter_module_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rootImageText',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 13, 37, 46, 288010)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 13, 37, 46, 288010)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 13, 37, 46, 288010)),
        ),
    ]
