# Generated by Django 4.1.7 on 2023-10-07 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_student_rootimagetext_alter_group_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 23, 41, 49, 564737)),
        ),
        migrations.AddField(
            model_name='class',
            name='Status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 23, 41, 49, 564737)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 23, 41, 49, 564737)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 23, 41, 49, 564737)),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='Venue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
