# Generated by Django 4.1.7 on 2023-10-10 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_class_date_alter_group_datecreated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currentAttendee',
            new_name='TheMdes',
        ),
        migrations.AlterField(
            model_name='class',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 33, 49, 959811)),
        ),
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 33, 49, 943771)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 33, 49, 943771)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 33, 49, 943771)),
        ),
    ]
