# Generated by Django 4.1.7 on 2023-10-10 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_currentattendee_themdes_alter_class_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themdes',
            old_name='Student',
            new_name='StudentId',
        ),
        migrations.AddField(
            model_name='themdes',
            name='StudentName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themdes',
            name='StudentSurname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 36, 7, 964204)),
        ),
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 36, 7, 964204)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 36, 7, 964204)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 21, 36, 7, 964204)),
        ),
    ]
