# Generated by Django 4.1.7 on 2023-10-11 02:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0010_themdes_type_alter_class_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 4, 24, 46, 355140)),
        ),
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 4, 24, 46, 355140)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 4, 24, 46, 355140)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 4, 24, 46, 354212)),
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('SecurityId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('PhoneNumber', models.CharField(default='+27', max_length=15)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('datecreated', models.DateField(default=datetime.datetime(2023, 10, 11, 4, 24, 46, 355140))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompusAttendee',
            fields=[
                ('CompusAttendeeId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('datecreated', models.DateField(default=datetime.date(2023, 10, 11))),
                ('dateTimeCreated', models.DateTimeField(default=datetime.datetime(2023, 10, 11, 4, 24, 46, 355140))),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
                ('takenBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
