# Generated by Django 4.1.7 on 2023-10-22 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_security_keeperimage_alter_class_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='rootImageText',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 49, 2, 377977)),
        ),
        migrations.AlterField(
            model_name='compusattendee',
            name='dateTimeCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 49, 2, 377977)),
        ),
        migrations.AlterField(
            model_name='group',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 49, 2, 377977)),
        ),
        migrations.AlterField(
            model_name='module',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 49, 2, 377977)),
        ),
        migrations.AlterField(
            model_name='program',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 49, 2, 377977)),
        ),
        migrations.AlterField(
            model_name='security',
            name='datecreated',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 17, 49, 2, 377977)),
        ),
    ]
